### ISSUE TITLE
Image2StyleGAN Paper?

### ISSUE THREAD

**Issue by olivercoad** [Puzer/stylegan#12]
Just read [this Image2StyleGAN paper](https://www.researchgate.net/publication/332300501_Image2StyleGAN_How_to_Embed_Images_Into_the_StyleGAN_Latent_Space) (also here https://arxiv.org/abs/1904.03189) and it thought it looked similar if not identical to this repo, but it doesn't appear to have any references to it.

@Puzer, Can you provide any insight on whether the paper and the work you've done in this repo are related, and if they are not the same, what are the differences?

**Comment by pbaylies** [comment]
@olivercoad I read that paper too; the loss function they end up with is a bit more complex, as they use both the L2 loss and several layers of VGG16; but one of their experiments (using a single layer of VGG16) is essentially the same as the solution in this repo, as far as I can tell. Also, they use Adam for the optimizer, and share the parameters they used for it.

**Comment by nile649** [comment]
Using extra loss function doesn't changes anything regards to idea... unless it is a new loss function introduced to deep learning community. Many authors leave their work open to such improvements...

**Comment by aarlo** [comment]
@Puzer Any thoughts on this? The results in the paper are really impressive.

**Comment by rom1504** [comment]
is there code for image2stylegan paper ?

**Comment by rom1504** [comment]
ok indeed based on what the paper says, it's really similar to this repo

**Comment by UPML** [comment]
The paper refers to this repo, but in the paper they use better loss function for optimizer. They use weighted sum of losses from different layers of VGG, instead only 9's layer as is in this code.

**Comment by olivercoad** [comment]
> The paper refers to this repo

The v2 version from September does actually include a reference.
