### ISSUE TITLE
Fast embeddings for head pose

### ISSUE THREAD

**Issue by jakeelwes** [Puzer/stylegan#15]
Hey just wondering if there was a simple way of getting fast embeddings just for the pose/coarse style (face landmarks & headPose). I was thinking of trying a realtime generator responding to movement through a webcam input - has anyone tried this & do you think it could be possible?

**Comment by pbaylies** [comment]
Hi @jakeelwes it's totally possible, @gradient-dissenter has done it. I'd suggest training a ResNet or similar to predict one or two of the coarse dlatents. I've got [code in my repo](https://github.com/pbaylies/stylegan-encoder) for training ResNets and EfficientNets, although out of the box it tries to predict all the dlatents.

**Comment by jakeelwes** [comment]
Amazing, thanks @pbaylies I'll give it a go :)
