### ISSUE TITLE
Question on Generating latent representation of your images

### ISSUE THREAD

**Issue by rperdon** [Puzer/stylegan#26]
I have a question on using your own images, how many images do you require of say Trump in order to generate a latent representation?

**Comment by jkyndir** [comment]
Just one.The result would be better if it was one where the face is facing forward with good lighting condition.

**Comment by rperdon** [comment]
Thanks for the response. I got it working with a single image. It turns out something odd with windows 10 paint format saving caused an issue with the image. I noted that some of my images when trying to run align_image.py on them that the resulting images would look greyscale and scanlined and some images were fine. By matching the correct bit depth and quality of the good images, I was able to get good latent images generated.
