### ISSUE TITLE
Issue with session and api

### ISSUE THREAD

**Issue by sandhyalaxmiK** [Puzer/stylegan#27]
I have created an API to run this github.
For the first client, everything is executing perfectly and giving  good result. But for the second client on the same session giving error like
ValueError: Tensor("Const:0", shape=(3,), dtype=float32) must be from the same graph as Tensor("strided_slice:0", shape=(1, 256, 256, 3), dtype=float32)

Trying to resolve the issue.
Help me for this.
Thanks & Regards,
Sandhya

**Comment by sandhyalaxmiK** [comment]
solved the problem

**Comment by robclouth** [comment]
How did you solve it?

**Comment by ramapinnimty** [comment]
@sandhyalaxmiK Can you please tell how did you solve it?
