### ISSUE TITLE
About 'Google Drive quota exceeded' error.

### ISSUE THREAD

**Issue by Michi-123** [Puzer/stylegan#37]
I got  'OSError: Google Drive quota exceeded' on Play_with_latent_directions.ipynb, especially line at 'dnnlib.util.open_url'. 

I don't know how to fix it.

Environment:
Google Colab
tensorflow-gpu==1.14

Running with bellow command. 
!git clone https://github.com/Puzer/stylegan-encoder.git

**Comment by JavierVillegas** [comment]
One way I found to solve the same error in other lines is to copy the  karras2019stylegan-ffhq-1024x1024.pkl  model in your own google drive and replace the link  for URL_FFHQ in encode_images.py by it.
Jeff Heaton explains it in  5:11 in https://www.youtube.com/watch?time_continue=8&v=RPGOPrkieTE&feature=emb_logo

**Comment by Michi-123** [comment]
Thanks a lot.
