### ISSUE TITLE
KeyError: "The name 'G_synthesis_1/_Run/concat:0' refers to a Tensor which does not exist. The operation, 'G_synthesis_1/_Run/concat', does not exist in the graph."

### ISSUE THREAD

**Issue by eluzzi5** [Puzer/stylegan#46]
Getting this error after running the following with TensorFlow 1.x in Google Colab on a GPU runtime:
!python encode_images.py aligned_images/ generated_images/ latent_representations/ --iterations 1000

Full error:
Traceback (most recent call last):
  File "encode_images.py", line 80, in <module>
    main()
  File "encode_images.py", line 53, in main
    generator = Generator(Gs_network, args.batch_size, randomize_noise=args.randomize_noise)
  File "/content/stylegan/encoder/generator_model.py", line 35, in __init__
    self.generator_output = self.graph.get_tensor_by_name('G_synthesis_1/_Run/concat:0')
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/ops.py", line 3783, in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/ops.py", line 3607, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/ops.py", line 3649, in _as_graph_element_locked
    "graph." % (repr(name), repr(op_name)))
KeyError: "The name 'G_synthesis_1/_Run/concat:0' refers to a Tensor which does not exist. The operation, 'G_synthesis_1/_Run/concat', does not exist in the graph."

Any help would be greatly appreciated!

**Comment by dagdelenmustafa** [comment]
Could you find a solution ?

**Comment by eluzzi5** [comment]
> Could you find a solution ?

No, I could not :(  Can anyone help?

**Comment by dagdelenmustafa** [comment]
Hey @eluzzi5 !!! 

I just discover that this repo uses tensorflow 1.14 and if you work on colab the versions does not match. And sometimes although the colab displays you are using GPU environment, tensorflow don't see your GPUs. So if you follow the following steps your problem might be solved.

Uninstall current tensorflow and install tensorflow 1.14:
`!pip uninstall -y tensorflow-gpu`
`!pip uninstall -y tensorflow`
`!pip install tensorflow-gpu==1.14`

Import tensorflow and check your version:
`import tensorflow`
`print(tensorflow.__version__)`

Finaly 
Check your availiable GPUs:
`tensorflow.test.is_gpu_available()`

**Comment by eluzzi5** [comment]
> Hey @eluzzi5 !!!
> 
> I just discover that this repo uses tensorflow 1.14 and if you work on colab the versions does not match. And sometimes although the colab displays you are using GPU environment, tensorflow don't see your GPUs. So if you follow the following steps your problem might be solved.
> 
> Uninstall current tensorflow and install tensorflow 1.14:
> `!pip uninstall -y tensorflow-gpu`
> `!pip uninstall -y tensorflow`
> `!pip install tensorflow-gpu==1.14`
> 
> Import tensorflow and check your version:
> `import tensorflow`
> `print(tensorflow.__version__)`
> 
> Finaly
> Check your availiable GPUs:
> `tensorflow.test.is_gpu_available()`

@dagdelenmustafa That fixed everything for me! Thank you SO much!
